# ============================
#  Global configuration
# ============================

# Treat TLS issues as warnings (not fatal)
insecure = true

# Accept typical redirect codes
accept = ["200", "301", "302", "307", "308"]

# Maximum redirect chain
max_redirects = 10

# Timeout per request (seconds) â€“ some smaller sites are slow
timeout = 30

# Do not include email validation
include_mail = false

# ============================
#  Exclusions (domains mit SSL/Bot-Problemen)
# ============================

exclude = [
    "https://www.malt.de",
    "https://www.projekt-broker.com"
]

